package report

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/sudo-jtcsec/noescope/internal/investigations/architecture"
	"github.com/sudo-jtcsec/noescope/internal/investigations/features"
	"github.com/sudo-jtcsec/noescope/internal/investigations/surface"
	"github.com/sudo-jtcsec/noescope/internal/model"
)

const maxFeatureRenderDepth = 32

func Markdown(application *model.Application) ([]byte, error) {
	var out bytes.Buffer
	projectName := inline(application.Metadata.ProjectName)
	if projectName == "" {
		projectName = "Application"
	}
	fmt.Fprintf(&out, "# %s\n\n", projectName)
	fmt.Fprintln(&out, "Generated by Noescope")
	fmt.Fprintf(&out, "\n- Git commit: `%s`\n", inline(application.Metadata.Source.GitCommit))
	fmt.Fprintf(&out, "- Git branch: `%s`\n", inline(application.Metadata.Source.GitBranch))
	fmt.Fprintf(&out, "- Repository state: %s\n", dirtyLabel(application.Metadata.Source.GitDirty))
	fmt.Fprintf(&out, "- Run: `%s`\n", inline(application.Metadata.RunID))
	fmt.Fprintf(&out, "- Generated: `%s`\n", application.Metadata.GeneratedAt.Format("2006-01-02T15:04:05Z07:00"))
	if application.Metadata.ApplicationURL != "" {
		fmt.Fprintf(&out, "- Application URL: `%s`\n", inline(application.Metadata.ApplicationURL))
	}

	renderInventory(&out, application)
	renderOverview(&out, application)
	renderAuthentication(&out, application)
	renderAuthorization(&out, application)
	renderEntities(&out, application)
	renderInterfaces(&out, application)
	renderIntegrations(&out, application)
	if err := renderFeatures(&out, application.Features); err != nil {
		return nil, err
	}
	renderUnresolved(&out, application)
	return out.Bytes(), nil
}

func renderInventory(out *bytes.Buffer, application *model.Application) {
	modules, nodes := features.Counts(&features.Findings{Features: application.Features})
	fmt.Fprintln(out, "\n## Application Inventory")
	fmt.Fprintf(out, "\n- Domain entities: %d\n", len(application.Entities))
	fmt.Fprintf(out, "- Application interfaces: %d\n", len(application.Surface.Interfaces))
	fmt.Fprintf(out, "- External integrations: %d\n", len(application.Surface.Integrations))
	fmt.Fprintf(out, "- Functional modules: %d\n", modules)
	fmt.Fprintf(out, "- Functional nodes: %d\n", nodes)
}

func renderOverview(out *bytes.Buffer, application *model.Application) {
	fmt.Fprintln(out, "\n## Overview")
	fmt.Fprintf(out, "\n- Architecture style: %s\n", valueOrUnknown(application.Architecture.ArchitectureStyle.Value))
	fmt.Fprintf(out, "- Languages: %s\n", technologyNames(application.Architecture.Languages))
	fmt.Fprintf(out, "- Frameworks: %s\n", technologyNames(application.Architecture.Frameworks))
	fmt.Fprintf(out, "- Databases: %s\n", technologyNames(application.Architecture.Databases))
	if len(application.Architecture.Entrypoints) == 0 {
		fmt.Fprintln(out, "- Main entrypoints: None documented")
	} else {
		fmt.Fprintln(out, "- Main entrypoints:")
		for _, entrypoint := range application.Architecture.Entrypoints {
			fmt.Fprintf(out, "  - `%s` (%s): %s\n", inline(entrypoint.Path), inline(entrypoint.Type), inline(entrypoint.Purpose))
		}
	}
}

func renderAuthentication(out *bytes.Buffer, application *model.Application) {
	findings := application.Identity.Authentication
	fmt.Fprintln(out, "\n## Authentication")
	fmt.Fprintf(out, "\n- Present: %s\n", yesNo(findings.AuthenticationPresent))
	fmt.Fprintf(out, "- Confidence: %.2f\n", findings.Confidence)
	if len(findings.Mechanisms) == 0 {
		fmt.Fprintln(out, "- Mechanisms: None documented")
		return
	}
	for _, mechanism := range findings.Mechanisms {
		fmt.Fprintf(out, "\n### %s\n", authenticationMechanismHeading(
			mechanism.Type,
			mechanism.ID,
		))
		fmt.Fprintf(out, "\n- Type: `%s`\n", inline(mechanism.Type))
		renderStringList(out, "Login entrypoints", mechanism.LoginEntrypoints, true)
		renderStringList(out, "Credential fields", mechanism.CredentialFields, false)
		if mechanism.Session != nil {
			session := mechanism.Session.Type
			if mechanism.Session.Name != "" {
				session += " (`" + inline(mechanism.Session.Name) + "`)"
			}
			if mechanism.Session.Storage != "" {
				session += ", storage: " + inline(mechanism.Session.Storage)
			}
			fmt.Fprintf(out, "- Session/token: %s\n", inline(session))
		}
		renderStringList(out, "Established by", mechanism.EstablishedBy, false)
		renderStringList(out, "Checked by", mechanism.CheckedBy, false)
		if mechanism.Logout != nil {
			renderStringList(out, "Logout entrypoints", mechanism.Logout.Entrypoints, true)
			if mechanism.Logout.Behavior != "" {
				fmt.Fprintf(out, "- Logout behavior: %s\n", inline(mechanism.Logout.Behavior))
			}
		}
	}
}

func authenticationMechanismHeading(mechanismType, id string) string {
	mechanismType = inline(mechanismType)
	id = inline(id)
	if mechanismType == "" {
		return id
	}
	if id == "" || id == mechanismType {
		return mechanismType
	}
	return mechanismType + " (`" + id + "`)"
}

func renderAuthorization(out *bytes.Buffer, application *model.Application) {
	findings := application.Identity.Authorization
	fmt.Fprintln(out, "\n## Authorization")
	fmt.Fprintf(out, "\n- Present: %s\n", yesNo(findings.AuthorizationPresent))
	fmt.Fprintf(out, "- Confidence: %.2f\n", findings.Confidence)
	if findings.Model != nil {
		fmt.Fprintf(out, "- Model: `%s`", inline(findings.Model.Type))
		if findings.Model.Description != "" {
			fmt.Fprintf(out, " — %s", inline(findings.Model.Description))
		}
		fmt.Fprintln(out)
	}
	if len(findings.Roles) > 0 {
		fmt.Fprintln(out, "\n### Roles")
		for _, role := range findings.Roles {
			fmt.Fprintf(out, "\n- `%s`", inline(role.ID))
			if role.Name != "" {
				fmt.Fprintf(out, " — %s", inline(role.Name))
			}
			if role.Description != "" {
				fmt.Fprintf(out, ": %s", inline(role.Description))
			}
			fmt.Fprintln(out)
		}
	}
	if len(findings.Permissions) > 0 {
		fmt.Fprintln(out, "\n### Permissions")
		const permissionLimit = 50
		limit := len(findings.Permissions)
		if limit > permissionLimit {
			limit = permissionLimit
		}
		for _, permission := range findings.Permissions[:limit] {
			fmt.Fprintf(out, "\n- `%s`", inline(permission.ID))
			if permission.Name != "" {
				fmt.Fprintf(out, " — %s", inline(permission.Name))
			}
			fmt.Fprintln(out)
		}
		if remaining := len(findings.Permissions) - limit; remaining > 0 {
			fmt.Fprintf(out, "\n- … %d additional permissions are preserved in `application.json`.\n", remaining)
		}
	}
	if len(findings.Enforcement) > 0 {
		fmt.Fprintln(out, "\n### Enforcement")
		for _, enforcement := range findings.Enforcement {
			location := enforcement.Path
			if enforcement.Symbol != "" {
				location += "#" + enforcement.Symbol
			}
			fmt.Fprintf(out, "\n- **%s** (`%s`)", inline(enforcement.Name), inline(enforcement.Type))
			if location != "" {
				fmt.Fprintf(out, " — `%s`", inline(location))
			}
			if enforcement.Description != "" {
				fmt.Fprintf(out, ": %s", inline(enforcement.Description))
			}
			fmt.Fprintln(out)
		}
	}
}

func renderEntities(out *bytes.Buffer, application *model.Application) {
	fmt.Fprintln(out, "\n## Domain Model")
	if len(application.Entities) == 0 {
		fmt.Fprintln(out, "\nNo domain entities were discovered.")
		return
	}
	for _, entity := range application.Entities {
		fmt.Fprintf(out, "\n### %s\n", inline(entity.Name))
		fmt.Fprintf(out, "\n%s\n", inline(entity.Description))
		fmt.Fprintf(out, "\n- ID: `%s`\n", inline(entity.ID))
		if len(entity.Aliases) > 0 {
			fmt.Fprintf(out, "- Aliases: %s\n", codeList(entity.Aliases))
		}
		if len(entity.Persistence) > 0 {
			values := make([]string, 0, len(entity.Persistence))
			for _, persistence := range entity.Persistence {
				values = append(values, persistence.Type+":"+persistence.Name)
			}
			fmt.Fprintf(out, "- Persistence: %s\n", codeList(values))
		}
		if len(entity.Relationships) > 0 {
			fmt.Fprintln(out, "- Relationships:")
			for _, relationship := range entity.Relationships {
				fmt.Fprintf(out, "  - `%s` → `%s`: %s\n", inline(relationship.Type), inline(relationship.TargetEntityID), inline(relationship.Description))
			}
		}
	}
}

func renderInterfaces(out *bytes.Buffer, application *model.Application) {
	fmt.Fprintln(out, "\n## Application Interfaces")
	renderSurfaceCoverage(out, application.Surface.Coverage)
	groups := []struct {
		name  string
		types map[string]bool
	}{
		{"Web", map[string]bool{"web_page": true, "form_action": true}},
		{"API", map[string]bool{"api_endpoint": true, "websocket": true}},
		{"CLI", map[string]bool{"cli_command": true, "script": true}},
		{"Workers / Jobs", map[string]bool{"scheduled_job": true, "worker": true, "event_consumer": true}},
		{"Other", map[string]bool{"other": true}},
	}
	for _, group := range groups {
		items := make([]surface.Interface, 0)
		for _, item := range application.Surface.Interfaces {
			if group.types[item.Type] {
				items = append(items, item)
			}
		}
		if len(items) == 0 {
			continue
		}
		fmt.Fprintf(out, "\n### %s\n", group.name)
		for _, item := range items {
			fmt.Fprintf(out, "\n#### %s\n", inline(item.Name))
			fmt.Fprintf(out, "\n%s\n", inline(item.Description))
			fmt.Fprintf(out, "\n- ID: `%s`\n", inline(item.ID))
			fmt.Fprintf(out, "- Locator: %s\n", interfaceLocator(item.Locator))
			if item.Access != nil {
				renderAccess(out, item.Access.Authentication, item.Access.RoleIDs, item.Access.PermissionIDs)
			}
			if len(item.EntityIDs) > 0 {
				fmt.Fprintf(out, "- Entities: %s\n", codeList(item.EntityIDs))
			}
		}
	}
}

func renderSurfaceCoverage(out *bytes.Buffer, coverage surface.Coverage) {
	items := []struct {
		name     string
		coverage surface.CategoryCoverage
	}{
		{"Web", coverage.Web},
		{"API", coverage.API},
		{"CLI", coverage.CLI},
		{"Background", coverage.Background},
		{"Integrations", coverage.Integrations},
	}
	fmt.Fprintln(out, "\n### Discovery Coverage")
	for _, item := range items {
		status := item.coverage.Status
		if status == "" {
			status = "not recorded"
		}
		fmt.Fprintf(
			out,
			"\n- %s: %s; applicable=%s; interfaces=%d; integrations=%d\n",
			item.name,
			inline(status),
			yesNo(item.coverage.Applicable),
			item.coverage.Interfaces,
			item.coverage.Integrations,
		)
	}
}

func renderIntegrations(out *bytes.Buffer, application *model.Application) {
	fmt.Fprintln(out, "\n## External Integrations")
	if len(application.Surface.Integrations) == 0 {
		fmt.Fprintln(out, "\nNo external integrations were discovered.")
		return
	}
	for _, integration := range application.Surface.Integrations {
		fmt.Fprintf(out, "\n### %s\n", inline(integration.Name))
		fmt.Fprintf(out, "\n%s\n", inline(integration.Description))
		fmt.Fprintf(out, "\n- ID: `%s`\n", inline(integration.ID))
		fmt.Fprintf(out, "- Type: `%s`\n", inline(integration.Type))
		fmt.Fprintf(out, "- Locator: %s\n", integrationLocator(integration.Locator))
		fmt.Fprintf(out, "- Authentication to dependency: `%s`\n", inline(integration.Authentication.Type))
		if integration.Authentication.CredentialSource != "" {
			fmt.Fprintf(out, "- Credential source: `%s`\n", inline(integration.Authentication.CredentialSource))
		}
		if len(integration.EntityIDs) > 0 {
			fmt.Fprintf(out, "- Entities: %s\n", codeList(integration.EntityIDs))
		}
	}
}

func renderFeatures(out *bytes.Buffer, nodes []features.Node) error {
	fmt.Fprintln(out, "\n## Functionality")
	if len(nodes) == 0 {
		fmt.Fprintln(out, "\nNo functionality was discovered.")
		return nil
	}
	for _, node := range nodes {
		if err := renderFeatureNode(out, node, 0); err != nil {
			return err
		}
	}
	return nil
}

func renderFeatureNode(out *bytes.Buffer, node features.Node, depth int) error {
	if depth >= maxFeatureRenderDepth {
		return fmt.Errorf("feature tree exceeds maximum render depth at %q", node.ID)
	}
	heading := depth + 3
	if heading > 6 {
		heading = 6
	}
	fmt.Fprintf(out, "\n%s %s\n", strings.Repeat("#", heading), inline(node.Name))
	fmt.Fprintf(out, "\n%s\n", inline(node.Description))
	fmt.Fprintf(out, "\n- ID: `%s`\n", inline(node.ID))
	fmt.Fprintf(out, "- Type: `%s`\n", inline(node.Type))
	renderAccess(out, node.Access.Authentication, node.Access.RoleIDs, node.Access.PermissionIDs)
	if len(node.EntityIDs) > 0 {
		fmt.Fprintf(out, "- Entities: %s\n", codeList(node.EntityIDs))
	}
	if len(node.InterfaceIDs) > 0 {
		fmt.Fprintf(out, "- Interfaces: %s\n", codeList(node.InterfaceIDs))
	}
	for _, child := range node.Children {
		if err := renderFeatureNode(out, child, depth+1); err != nil {
			return err
		}
	}
	return nil
}

func renderUnresolved(out *bytes.Buffer, application *model.Application) {
	stages := []struct {
		name  string
		stage model.StageProvenance
	}{
		{"Architecture", application.Discovery.Stages.Architecture},
		{"Authentication", application.Discovery.Stages.Authentication},
		{"Authorization", application.Discovery.Stages.Authorization},
		{"Domain Entities", application.Discovery.Stages.Entities},
		{"Technical Surface", application.Discovery.Stages.Surface},
		{"Features", application.Discovery.Stages.Features},
	}
	count := 0
	for _, item := range stages {
		count += len(item.stage.Unresolved)
	}
	if count == 0 {
		return
	}
	fmt.Fprintln(out, "\n## Unresolved Questions")
	for _, item := range stages {
		if len(item.stage.Unresolved) == 0 {
			continue
		}
		fmt.Fprintf(out, "\n### %s\n", item.name)
		for _, unresolved := range item.stage.Unresolved {
			fmt.Fprintf(out, "\n- **%s**", inline(unresolved.Question))
			if unresolved.Priority != "" {
				fmt.Fprintf(out, " (`%s`)", inline(unresolved.Priority))
			}
			if unresolved.Reason != "" {
				fmt.Fprintf(out, " — %s", inline(unresolved.Reason))
			}
			fmt.Fprintln(out)
		}
	}
}

func renderAccess(out *bytes.Buffer, authentication string, roleIDs, permissionIDs []string) {
	fmt.Fprintf(out, "- Access: %s\n", accessLabel(authentication))
	if len(roleIDs) > 0 {
		fmt.Fprintf(out, "- Roles: %s\n", codeList(roleIDs))
	}
	if len(permissionIDs) > 0 {
		fmt.Fprintf(out, "- Permissions: %s\n", codeList(permissionIDs))
	}
}

func interfaceLocator(locator surface.InterfaceLocator) string {
	parts := make([]string, 0, 7)
	if locator.Method != "" {
		parts = append(parts, locator.Method)
	}
	for _, value := range []string{locator.Path, locator.Command, locator.Schedule, locator.Event} {
		if value != "" {
			parts = append(parts, value)
		}
	}
	if locator.Protocol != "" {
		parts = append(parts, "protocol="+locator.Protocol)
	}
	if locator.MethodName != "" {
		parts = append(parts, "method_name="+locator.MethodName)
	}
	if locator.TransportPath != "" {
		parts = append(parts, "transport_path="+locator.TransportPath)
	}
	return codeList(parts)
}

func integrationLocator(locator surface.IntegrationLocator) string {
	parts := make([]string, 0, 5)
	if locator.Method != "" {
		parts = append(parts, locator.Method)
	}
	for _, value := range []string{locator.BaseURL, locator.Path, locator.Name, locator.Command} {
		if value != "" {
			parts = append(parts, value)
		}
	}
	return codeList(parts)
}

func technologyNames(values []architecture.Technology) string {
	if len(values) == 0 {
		return "None documented"
	}
	names := make([]string, 0, len(values))
	for _, value := range values {
		names = append(names, value.Name)
	}
	return codeList(names)
}

func renderStringList(out *bytes.Buffer, label string, values []string, code bool) {
	if len(values) == 0 {
		return
	}
	if code {
		fmt.Fprintf(out, "- %s: %s\n", label, codeList(values))
		return
	}
	clean := append([]string(nil), values...)
	sort.Strings(clean)
	for i := range clean {
		clean[i] = inline(clean[i])
	}
	fmt.Fprintf(out, "- %s: %s\n", label, strings.Join(clean, "; "))
}

func codeList(values []string) string {
	if len(values) == 0 {
		return "None documented"
	}
	clean := append([]string(nil), values...)
	sort.Strings(clean)
	for i := range clean {
		clean[i] = "`" + inline(clean[i]) + "`"
	}
	return strings.Join(clean, ", ")
}

func accessLabel(value string) string {
	switch value {
	case "required":
		return "Authentication required"
	case "not_required":
		return "Authentication not required"
	default:
		return "Authentication unknown"
	}
}

func yesNo(value bool) string {
	if value {
		return "Yes"
	}
	return "No"
}

func dirtyLabel(dirty bool) string {
	if dirty {
		return "dirty"
	}
	return "clean"
}

func valueOrUnknown(value string) string {
	if value == "" {
		return "Unknown"
	}
	return inline(value)
}

func inline(value string) string {
	return strings.Join(strings.Fields(value), " ")
}
